### PR TITLE
match_dir fix

### LINKED ISSUE #108: --match_dir does not work properly
The `--match_dir` is not respected properly when multiple directories exist:

````
> mkdir bar
> mkdir bat
> mkdir baz
> touch bar/bar.py
> touch bat/bat.py
> touch baz/baz.py
> pep257 --match-dir=bar
./bar/bar.py:1 at module level:
        D100: Docstring missing
./baz/baz.py:1 at module level:
        D100: Docstring missing
````

`bar` is correctly matched, and `bat` is correctly excluded, but `baz` is incorrectly included.

I have a candidate fix for this - will submit pull request.

### PR DESCRIPTION
**Pull request by glennmatthews**
Fixes #108 by properly modifying `dirs` in place.

### CODE REVIEW

**Comment by Nurdok** [comment]
@glennmatthews thank you so much for your time. Merged!

**Comment by jawshooah** [comment]
@Nurdok can we get a new release with this fix? With 0.4.1, `pep257` keeps reporting errors about files in my `.tox` directory no matter how I specify `match-dir`.

**Comment by Nurdok** [comment]
Released in 0.5.0
http://pep257.readthedocs.org/en/latest/release_notes.html#march-14th-2015

**Comment by jawshooah** [comment]
Awesome, thanks!

**Pull request merged**
