### PR TITLE
DRY in error definitions

### PR DESCRIPTION
**Pull request by Nurdok**
This PR does several things:

* Instead of each check returning an arbitrary error, all errors are defined beforehand.
* All defined errors are also put in a registry that hold them in groups (D1xx, D2xx, etc.)
* Instead of explicitly putting the error description in both the docs and the code, the error code table is generated from the error registry in the script.

The reasons are:

1. DRY (Don't Repeat Yourself). Having more than one location where errors are defined is... error prone :) And already I found that the error table from the docs had somewhat different error descriptions than the ones reported by the script.
2. Having a list of all the possible error code, instead of defining them only when an error is found by a check, will help to implement #96, by allowing to easily compile a list of selected errors whether the user specified them by a whitelist or a blacklist.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
So you actually do repeat yourself still a bit with stuff like:

```py
D1xx.create_error(...)
# 4 more times
```

Granted there will be groups (or classes) that only have one error, so `create_error` is a great method. What about, also having, `create_errors` that takes a dictionary. So the usage would look like:

```py
D1xx.create_errors({
    'D100': ('Missing docstring in public module', ),
    'D101': ('...', ),
    # ...
})
D2xx.create_errors({ ... })
```

And `create_errors` would look like:

```py
def create_errors(self, error_dictionary):
    errors = []
    for error_code in error_dictionary:
        errors.append(self.create_error(error_code, *error_dictionary[error_code]))
    return errors
```

This has the unfortunate side-effect of making it harder to change `create_error`'s signature (but you were already using positional calling for an optional parameter, so it won't make it that bad).

**Comment by Nurdok** [comment]
@sigmavirus24 It did bother me a little, but the problem is that I need to assign the return value to a name, e.g.,

    D100 = D1xx.create_error('D100', 'Missing docstring in public module')

So that `D100` will be available as a return value for its corresponding check. Defining several errors in one call will not allow this, or make this cumbersome (if the call will return a tuple of errors).

**Comment by sigmavirus24** [comment]
You already keep track of the errors (and keep them in an order of creation). You could use that to your advantage. You could do:

```py
D1xx.create_errors([
    ('00', ('Missing docstring in public module',)),
    ('01', ('...', )),
    # ...
])
D100, D101, D102, D103, D104 = D1xx.errors
```

Using the list of tuples will ensure the ordering is correct. Further, since `D1xx` is already created with a prefix, you can simplify how you create the errors by modifying `create_error` to do:

```py
def create_error(self, error_code, error_desc, error_context=None):
    class _Error(Error):
        code = self.prefix + error_code.lstrip(self.prefix)
        short_desc = error_desc
        context = error_context
    self.errors.append(_Error)
    return _Error
```

Using `lstrip` will allow you to not have to refactor the calls much as they are right now.

I'm not sure how I see this as being more cumbersome than the current code (in my opinion).

**Comment by Nurdok** [comment]
I've given this a lot of thought and I am ambivalent about this. I see your point of the calls repeating themselves, but I find that when dealing with these sort of "declarative" code blocks, I prefer to be explicit and simple rather than efficient and complex. However minor the the differences are in this case. So I decided to go ahead with the original version - but I whole heatedly appreciate your involvement in this PR, and many others in this project. Thanks!

**Pull request merged**
